#!/bin/bash
# params: [TYPE] [COMMAND_NAME]
# desc: allows you to generate a command or an alias
# TYPE: command 
# COMMAND_NAME: name of the command you want to generate
# examples:
# $project generate command 
# 

echo "Argument missing"
echo 

show_help "generate"
